parameters:
  SolutionBaseName:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 2.2
  variables:
  - group: BUILD Management Resources
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml
      
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloud: true
      SonarCloudProjectKey: SkillsFundingAgency_das-levy-transfer-matching-functions

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish ${{ parameters.SolutionBaseName }}
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c release --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - LevyTransferMatchingFunctions
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: LevyTransferMatchingFunctions
